# $NetBSD$

DISTNAME=	zabbix-2.2.1
CATEGORIES=	smartos-packages_jn
MASTER_SITES=	http://netcologne.dl.sourceforge.net/project/zabbix/ZABBIX%20Latest%20Stable/2.2.1/

MAINTAINER=	jens@neuhalfen.name
HOMEPAGE=	http://netcologne.dl.sourceforge.net/project/zabbix/ZABBIX%20Latest%20Stable/2.2.1/
COMMENT=	Enterprise monitoring
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=		yes
USE_PKGLOCALEDIR=	yes
USE_LANGUAGES=		c c++

.include "../../mk/bsd.pkg.mk"
